### ISSUE TITLE
GSVA: Error in (function (classes, fdef, mtable)  :    unable to find an inherited method for function ‘gsva’ for signature ‘"spec_tbl_df", "missing"’

### ISSUE THREAD

**Issue by AlekoteMX** [rcastelo/GSVA#14]
Hi, guys. I tired to use GSVA for calculation of score of each immune cell type in a TCGA RNAseq follow Wang et al. 's instruction at https://xsliulab.github.io/tumor-immunogenicity-score/#calculation-of-aps-tis-and-iis. 
After dowlnloading data from UCSC Xena, and tiding and cleanning the RNAseq and clinical data, I tried:
load("results/merged_geneList.RData")
load("results/TCGA_RNASeq_PanCancer.RData")
gsva(ExprMatList = list(TCGA_RNASeq_PanCancer), merged_geneList, group_col = "Cell_type", gene_col = "Symbol", method = "gsva")-> res_pancan.GSVA
then I saw this error:
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘gsva’ for signature ‘"spec_tbl_df", "missing"’
I am not sure if it's beacuse there maybe some NA in the RNAseq dataset, or because I need to change the dataframe for this gvsa function.
Could someone please enlighten me?
Thanks in advance!

**Comment by rcastelo** [comment]
hi @AlekoteMX 

Apologies for the delay in getting back to your question. Next time, please use the Bioconductor support site at https://support.bioconductor.org to post questions about using GSVA. The issues tab in this GitHub site are more intended for development questions and feature requests.

Note that the protocol in the URL you are giving is not calling directly the GSVA interface, which is just the function 'gsva()', but some kind of wrapper function called 'applyGSVA()', which different arguments as the 'gsva()' function. More concretely the 'gsva()' function is prompting an error because it does not recognize the arguments 'ExprMatList', 'group_col' or 'gene_col'. You should read the GSVA documentation (manual and vignette) available from the GSVA landing [page](https://bioconductor.org/packages) to learn how to call the function 'gsva()'.

I'm going to close this issue. If you have further questions, please post them at the Bioconductor support site but, before you do that, please read carefully the [Bioconductor posting guide](https://www.bioconductor.org/help/support/posting-guide).
