### ISSUE TITLE
loading gsva causing R to encounter fatal error

### ISSUE THREAD

**Issue by rg510** [rcastelo/GSVA#141]
I have been trying to use the GSVA package. With R version 4.3.1 and bioconductor 3.17, BioManager::install("GSVA") was downloading GSVA version 1.48 (I think 1.48.1 or 1.48.3). Although this was installing and loading fine, the function gsvaParam() 'could not be found'. 

I therefore updated Bioconductor to 3.18 (R 4.3.2 was also required for this) and then GSVA version 1.50.0. Unfortunately now loading GSVA: library(GSVA) causes 'a fatal error in R' requiring the session to be restarted. 

Not quite sure what is causing the error, there is nothign further displayed

This is the session info just before I try to run library(GSVA)

> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Big Sur 11.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/London
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] BiocManager_1.30.22 compiler_4.3.2      Matrix_1.6-5        cli_3.6.2           tools_4.3.2         Rcpp_1.0.12        
 [7] reticulate_1.35.0   grid_4.3.2          jsonlite_1.8.8      rlang_1.1.3         png_0.1-8           lattice_0.22-5     
> 

Many thanks for any advice. Apologies if ive not provided enough info/correctly formatted info

**Comment by rg510** [comment]
In the end, Ive uninstalled libraries then reinstalled the earlier version of GSVA
> options(renv.settings.bioconductor.version = "3.17")
> renv::install("bioc::GSVA@1.48.3")

and then passed the matrix and geneset directly to the gsva() without using the gsvaParam() function first

Seems to generate the expected the expected results so guessing that's all okay? 

thanks very much

**Comment by rcastelo** [comment]
Hi,

GSVA builds, installs and checks without errors or warnings in a number of platforms including linux, windows and macOS as reported in the Bioconductor build system here:

https://www.bioconductor.org/checkResults/3.18/bioc-LATEST/GSVA

according to your session information, your system is macOS BigSur on an arm64 architecture, which as far as I can see, it is not part of the Bioconductor build system since the two macOS systems that they are testing are Monterey x86_64 and Ventura arm64. I use a macOS Ventura x86_64 laptop, so I cannot test GSVA either in the arm64 architecture.

We always recommend to use the latest release version of R and the Bioconductor packages and in the case of GSVA this is even more relevant now, because we have deprecated the interface and introduced a new object-oriented one, which is the one described now in the vignette. GSVA and the rest of Bioconductor packages only get bugfixes in the current release, which is another reason to try using always the release version of Bioconductor packages. So, I think it's important that we figure out what the problem is somehow. My intution says that the problem might be related to loading some of the GSVA package dependencies. Could you please load them one by one, to check if you pinpoint which of them causes the crash?

Just copy&paste the following instructions on your R shell one by one:

```r
library(S4Vectors)
library(IRanges)
library(Biobase)
library(SummarizedExperiment)
library(GSEABase)
library(Matrix)
library(parallel)
library(BiocParallel)
library(SingleCellExperiment)
library(sparseMatrixStats)
library(DelayedArray)
library(DelayedMatrixStats)
library(HDF5Array)
library(BiocSingular)
```

Thanks!
