### ISSUE TITLE
Type of output from gsva()

### ISSUE THREAD

**Issue by Chrisdoan9** [rcastelo/GSVA#155]
Hi team,

I don't know why my output from `gsva()` is **large matrix** meanwhile on the vignette it is **formal class ExpressionSet**. Seem if I don't use `gsvaParam()` as this tutorial, the type of output will be different. May I know how should I modify to apply for all gene sets in C2? I don't grep up and down pathways but all my different express paths are pathways end with UP and DN like HEPARD_CRUSH_AND_BURN_MUTANT_DN or CAFFAREL_RESPONSE_TO_THC_UP. c2BroadSets have 3272 pathways in total I think.

```
leukPar <- gsvaParam(microarray_exp_set, cgpC2BroadSets,
                     minSize=10, maxSize=500)
```

https://alexslemonade.github.io/refinebio-examples/02-microarray/pathway-analysis_microarray_03_gsva.html#45_Perform_differential_expression_on_pathway_scores
Thank you so much!

**Comment by axelklenk** [comment]
Hi Chris,

`gsva()` strives to return the same data type you have provided as an input in order to preserve, as much as possible, the metadata a class like `ExpressionSet` may contain.  The tutorial you are pointing to is using a matrix and hence a matrix should be returned.

I'd *strongly encourage* the use of GSVA's new object-oriented API via `gsvaParam()` as this will be the basis for further development and improvement.  The old API used in the tutorial should already have given you a deprecation warning and will become defunct and subsequently removed with the next Bioconductor release *in about four weeks*.

I'm not sure I understand what you are asking about the pathways -- but `gsva()` does not modify the gene sets from your `cgpC2BroadSets` in any way except filtering for gene set size according to arguments `minSize` / `maxSize` and omitting any genes it cannot find in your expression data matrix.

Hope this helps.

**Comment by Chrisdoan9** [comment]
Hi Axel,

Thank you so much for the detail reply! I mean how can I apply gsva to all pathway in C2 gene set which is 7,233 gene sets?
The way that tutorial used is to download the gmt file like this:

`gmt_url <- "https://data.broadinstitute.org/gsea-msigdb/msigdb/release/7.5/c2.all.v7.5.entrez.gmt"`

So it has all 7,233 gene sets in total. If I use: 
```
leukPar <- gsvaParam(microarray_exp_set, c2BroadSets,
                     minSize=10, maxSize=500)
```
I think it only has 3,272 gene sets.

**Comment by axelklenk** [comment]
If I download that file and look at it, it contains 6,365 gene sets, of which 5,435 pass your filter settings of 10 <= n <= 500.
This is MSigDB **release 7.5 from January 2022**.

The ***current*** MSigDB **release 2023.1.Hs** appears to have 7,233 gene sets and is at https://data.broadinstitute.org/gsea-msigdb/msigdb/release/2023.1.Hs/c2.all.v2023.1.Hs.entrez.gmt

**Comment by axelklenk** [comment]
Correction: current is 2023.2.Hs: https://data.broadinstitute.org/gsea-msigdb/msigdb/release/2023.2.Hs/c2.all.v2023.2.Hs.entrez.gmt

**Comment by Chrisdoan9** [comment]
Hi Axel,

Thank you so much for a nice catch! When I try:
```
gene_set_list <- qusage::read.gmt(gmt_file)
Par <- gsvaParam(data, gene_set_list,
                     minSize=1, maxSize=500)
gsva_results <- gsva(Par)
```
I got the same result as:

```
gsva_results <- gsva(
  data,
  gene_set_list,
  method = "gsva",
  # Appropriate for our log2-transformed microarray data
  kcdf = "Gaussian",
  # Minimum gene set size
  min.sz = 1,
  # Maximum gene set size
  max.sz = 500,
  # Compute Gaussian-distributed scores
  mx.diff = TRUE,
  # Don't print out the progress bar
  verbose = FALSE
)
```

**Comment by axelklenk** [comment]
Hi Chris,

ok, same results as expected.  Everything's fine then or any further questions/issues?

Let me repeat that we strongly recommend using the new API as in
```
Par <- gsvaParam(data, gene_set_list,
                     minSize=1, maxSize=500)
gsva_results <- gsva(Par)
```

since the old API will stop working with the upcoming Bioconductor 3.19 in about four weeks.

**Comment by Chrisdoan9** [comment]
Hi Axel,

No question about this topic. From now, I always use `gsvaParam()` before `gsva()`. Thank you!
