### ISSUE TITLE
GSVA on multiple datasets

### ISSUE THREAD

**Issue by komalsrathi** [rcastelo/GSVA#17]
Hi,

I am trying to calculate GSVA scores from RNA gene expression data from TCGA adult tumors (n = 9000 samples) and a bunch of pediatric tumors from another dataset (OpenPBTA;  n = 970 samples). Although, these are two different datasets, we have all the data harmonized using the same pipeline. 

When running with the combined dataset of  adult + pediatric tumors (~10000 samples and 30,000 genes) I am getting an error:

```
gsea_scores <- gsva(expr = total.matrix, # log transformed FPKM values
                          gset.idx.list =  geneset, 
                          method = "gsva",
                          min.sz = 1, max.sz = 50,
                          mx.diff = TRUE, 
                          verbose = FALSE) 

vector limit exhausted
```

I was wondering what is the recommended route here when the sample size is large: should I combine and run all datasets (nearly 11000 samples) together or should I run the TCGA adult tumors separately and OpenPBTA pediatric tumors separately? If the latter is possible, are separately computed GSVA scores comparable? 

Thanks,
Komal

**Comment by rcastelo** [comment]
Hi Komal,

If the raw data have been processed uniformly, you can run GSVA on all the data together and expect sensible results. GSVA scores calculated independently from multiple datasets are not comparable in the sense that their values may mean different things in different datasets. However, you can always try to apply some omics integration technique (sparse canonical correlation analysis, MOFA, etc.) to combine them. We just had a discussion about how comparable are GSVA scores from a subset of the data with respect to the whole data in this [thread](https://support.bioconductor.org/p/130889) at the Bioconductor support site, which may help you understand why GSVA scores depend on the input data.

With respect to the error, the very last version of GSVA 1.36.0 just released a couple of weeks ago with the latest Bioconductor 3.11, allows one to perform the calculations for those large matrices in parallel using the `BiocParallel` package through a new argument `BPPARAM` in the `gsva()` function. I could run it in my laptop with 8Gb of RAM on a matrix with 20K genes and 10K samples.

However, if you're already running the last version of GSVA, to find out the problem you would have to report the output of `traceback()` right after the error and of `sessionInfo()` to be able to help you. It would be great if you can do that at the [Bioconductor support site](https://support.bioconductor.org) since the solution will be more easily discoverable for other users with the same problem.
