### ISSUE TITLE
gsva()function

### ISSUE THREAD

**Issue by eliauk07yz** [rcastelo/GSVA#170]
Excuse me：
parallel.sz=32 and verbose=False in the old version of gsva method. How to add and use the gsvaParam () method in the new version

**Comment by axelklenk** [comment]
Hi, parallelism and verbosity are not part of GSVA's parameter objects and the corresponding arguments can be passed to `gsva(.)` in addition to a parameter object e.g. 
```
gp <- gsvaParam(X, gs)
gsva(gp, verbose=FALSE, BPPARAM=MulticoreParam(workers=32))
```
i.e. `verbose`works exactly as before (note, however, `FALSE` instead of False) while `parallel.sz` is replaced by Bioconductor's `BiocParallel` framework: https://bioconductor.org/packages/release/bioc/html/BiocParallel.html which supports various parallel backends in a flexible and portable way.

The example above is using `MulticoreParam(.)` for forked processes on multicore CPUs.  Please see the `BiocParallel` documentation and vignette for more information.

Please don't hesitate to get back to us if this should not answer your question.

**Comment by eliauk07yz** [comment]
Thanks
