### ISSUE TITLE
The data type of  exprData matrix: for ssgseaParam, integer counts?  Continuous expression data?

### ISSUE THREAD

**Issue by jnhv** [rcastelo/GSVA#171]
Dear Developer,

**Thank you for your outstanding work – it's been incredibly helpful!**

Quick question: What's the ideal input for `ssgseaParam`—continuous expression data (e.g., log-scale microarray, RNA-seq log-CPMs/RPKMs/TPMs) or integer counts from RNA-seq? Additionally, I noticed that when using `gsvaParam`, users have the flexibility to adjust parameters like `kcdf`. However, it appears that this level of customization is not offered within `ssgseaParam`. 

 Could you shed some light on this discrepancy or perhaps guide me towards any alternative means to achieve similar functionality within the context of `ssgseaParam`?

Thank you once again for your dedication and for considering my request.

Best regards,
Jin

**Comment by rcastelo** [comment]
Hi, thanks for using GSVA!

The `ssgseaParam()` constructor function serves the purpose of building a parameter object to use the ssGSEA method first published by [Barbie et al. (2009](https://doi.org/10.1038/nature08460), see Online Methods, subsection 'Signature projection method'), which is not a method we developed, we only provide an efficient implementation of this method in R and Bioconductor. I'd say probably ssGSEA works best with normalized logCPM or logTPM units of expression, but you may get a more authorative answer in the official support site for ssGSEA, which I believe is this [Google Group](https://groups.google.com/g/genepattern-help/search?q=ssgsea).

Regarding the question about why the `ssgseaParam()` function has different arguments than the `gsvaParam()` function, the reason is that these function build parameter objects for different methods, i.e., the GSVA method is different from the ssGSEA method. You may find this discussed in the [GSVA paper](https://doi.org/10.1186/1471-2105-14-7).

cheers,

robert.

**Comment by jnhv** [comment]
thank you！！！

**Comment by jnhv** [comment]
> Hi, thanks for using GSVA!
> 
> The `ssgseaParam()` constructor function serves the purpose of building a parameter object to use the ssGSEA method first published by [Barbie et al. (2009](https://doi.org/10.1038/nature08460), see Online Methods, subsection 'Signature projection method'), which is not a method we developed, we only provide an efficient implementation of this method in R and Bioconductor. I'd say probably ssGSEA works best with normalized logCPM or logTPM units of expression, but you may get a more authorative answer in the official support site for ssGSEA, which I believe is this [Google Group](https://groups.google.com/g/genepattern-help/search?q=ssgsea).
> 
> Regarding the question about why the `ssgseaParam()` function has different arguments than the `gsvaParam()` function, the reason is that these function build parameter objects for different methods, i.e., the GSVA method is different from the ssGSEA method. You may find this discussed in the [GSVA paper](https://doi.org/10.1186/1471-2105-14-7).
> 
> cheers,
> 
> robert.

thank you！！！
