### ISSUE TITLE
Error:  Calling gsva(expr=., gset.idx.list=., method=., ...) is defunct; use a method-specific parameter object (see '?gsva'). 

### ISSUE THREAD

**Issue by jiangych17** [rcastelo/GSVA#173]
>afgeneSet=list(Drug=genes)
>af.final <- irGSEA.score(object = af, assay = "RNA", slot = "data", seeds = 123, ncores = 1,msigdb=F, custom = T, geneset = afgeneSet, method =  c("AUCell", "UCell", "singscore", "ssgsea"), kcdf = 'Gaussian')

Error:  Calling gsva(expr=., gset.idx.list=., method=., ...) is defunct; use a method-specific parameter object (see '?gsva').

**Comment by rcastelo** [comment]
hi, the message you are reporting indicates that you are using the package [irGSEA](https://github.com/chuiqin/irGSEA) to call GSVA, so the problem is in the way in which irGSEA calls GSVA. I can see that somebody already opened an [issue in the irGSEA GitHub repo](https://github.com/chuiqin/irGSEA/issues/43) about this problem, so if you want to use GSVA through irGSEA, you will have to wait until the irGSEA authors fix it.

The problem itself stems from a change me made to the GSVA API, on October 2023 we introduced the new API and deprecated the way in which the `gsva()` function was called until then, which meant that a warning was being given when the old API was used. On April 2024 we defunct the old API, which means that an error is prompted when attempting to use the old API and this is what is happening right now with the irGSEA package. We did notify in December the maintainers of packages in the CRAN and Bioconductor repositories that depend on GSVA to update the way in which their packages were calling the `gsva()` function. Apparently, irGSEA is not neither in CRAN or Bioconductor, and therefore we could not warn the authors of irGSEA about this change. There is no way for us to know what repos in GitHub, among the more than 400 million public repos, may be using GSVA. In any case, had the authors of irGSEA monitored whether their package builds and checks without warning, they would have spotted in October the deprecation warning.

I'm sorry we cannot be of more help here.
