### ISSUE TITLE
Problems encountered when calculating GSVA with large single-cell data

### ISSUE THREAD

**Issue by sjasws** [rcastelo/GSVA#178]
Dear Developer,
I am now calculating GSVA score with large single-cell data (30,000 genes * 80,000 cells). When I processed the gsvaParam() function, it warned me that the data is too large:
In asMethod(object) :
  sparse->dense coercion: allocating vector of size 20.9 GiB
Then I run the gsva() function to calculate the score, and encounter error with:
Error in compute.gene.density(expr, sample.idxs, rnaseq, kernel): 
  negative length vectors are not allowed
I found this is because that R can not pass the data more than 2^31 elements (there is 2803945048 elements in my data). So I split the data and ran the calculations again. But new problems happened. I found that when the whole data was divided to different parts, I got different GSVA score for the same cell in the same pathway. I doubt if the data can be divided to score and then to merge.
So now I would like to ask you if you have a better solution? Thank you!

**Comment by rcastelo** [comment]
Dear @sjasws we are working right now to facilitate that GSVA works with large single-cell data, which we expect to be possible by the next release of the software in October. In the meantime you can try reducing the size of your data by discarding low-quality cells and lowly-expressed genes, which does not only serves the purpose of reducing the size of the data, but also of reducing the amount of noisy data you input to GSVA:

1. Filter out low quality cells. Assuming your single-cell data is stored in a `SingleCellExperiment` object (let me know otherwise) called `sce`:

```r
library(scuttle)

is_mito <- grepl("^MT-", rowData(sce)$Symbol_TENx)
qcstats <- perCellQCMetrics(sce, subsets=list(Mito=is_mito))
filtered <- quickPerCellQC(qcstats, percent_subsets="subsets_Mito_percent")
sce <- sce[, !filtered$discard]
```

2. Filter out lowly-expressed genes. You could filter out genes with, let's say, less than 2000 UMI counts across all the 80,000 cells, as follows:

```r
cntxgene <- rowSums(assays(sce)$counts)+1
sce <- sce[cntxgene > 2000, ]
```
one way to make a more informed selection of the minimum number of UMI counts is to look at the empirical cumulative distribution function (ECDF) in log scale of the total number of UMI counts per gene as follows:

```r
plot.ecdf(cntxgene, xaxt="n", panel.first=grid(), xlab="UMI counts per gene",
                    las=1, log="x", xlim=c(1, 10e5), main="")
axis(1, at=10^(0:5), labels=10^(0:5))
```
and then select the cutoff where the ECDF starts becoming steep. Please let me know whether doing this you can run the algorithm.

**Comment by sjasws** [comment]
> Dear @sjasws we are working right now to facilitate that GSVA works with large single-cell data, which we expect to be possible by the next release of the software in October. In the meantime you can try reducing the size of your data by discarding low-quality cells and lowly-expressed genes, which does not only serves the purpose of reducing the size of the data, but also of reducing the amount of noisy data you input to GSVA:
> 
> 1. Filter out low quality cells. Assuming your single-cell data is stored in a `SingleCellExperiment` object (let me know otherwise) called `sce`:
> 
> ```r
> library(scuttle)
> 
> is_mito <- grepl("^MT-", rowData(sce)$Symbol_TENx)
> qcstats <- perCellQCMetrics(sce, subsets=list(Mito=is_mito))
> filtered <- quickPerCellQC(qcstats, percent_subsets="subsets_Mito_percent")
> sce <- sce[, !filtered$discard]
> ```
> 
> 2. Filter out lowly-expressed genes. You could filter out genes with, let's say, less than 2000 UMI counts across all the 80,000 cells, as follows:
> 
> ```r
> cntxgene <- rowSums(assays(sce)$counts)+1
> sce <- sce[cntxgene > 2000, ]
> ```
> 
> one way to make a more informed selection of the minimum number of UMI counts is to look at the empirical cumulative distribution function (ECDF) in log scale of the total number of UMI counts per gene as follows:
> 
> ```r
> plot.ecdf(cntxgene, xaxt="n", panel.first=grid(), xlab="UMI counts per gene",
>                     las=1, log="x", xlim=c(1, 10e5), main="")
> axis(1, at=10^(0:5), labels=10^(0:5))
> ```
> 
> and then select the cutoff where the ECDF starts becoming steep. Please let me know whether doing this you can run the algorithm.

Dear @rcastelo ,
I followed your advice but still can not run the algorithm.
I have filtered out the low quality cells, and then filtered out lowly-expressed genes with more than 2000 UMI counts. I found the UMI vs logECDF curve is not suitable to filter low-expressed genes for my data, because it did not show a steep point:
[UMIvsFn.pdf](https://github.com/user-attachments/files/16344360/UMIvsFn.pdf)
But after all, the large data with more than 2^31 elements has been reduced to small enough (about 16,000 genes * 80,000 cells) to run the gsva() function.
However, this process have been running for more than 2 days but still stuck at the stage of "Estimating ECDFs with Gaussian kernels". My computer is with Windows system and only uses single-core computing at 4.6GHz. To speed up the process, I also use 50 core operations with gsva(gsva_Par,BPPARAM=MulticoreParam(workers=50)) in the computer cluster, but I get an Error: Error in mcfork(detached) :
unable to fork, possible reason: Cannot allocate memory.
I tried to find out what made the process so slow, and it turned out that the number of cells (ncol), not the number of genes (nrow), was the main factor affecting the speed of the process. After sampling 10,000 cells, even if the number of genes is maintained at 30,000, the calculation of gsva score can still be completed in about 1 hour.

I am currently using R 4.4.1, GSVA 1.52.3, Seurat 5.1.0. The code I run is as follows:
library(Seurat)
library(GSVA)
library(GSEABase)
load("Tumor.RData")  #load my data
DefaultAssay(obj) <- "RNA"
obj <- JoinLayers(obj)
obj <- NormalizeData(obj)
cntxgene <- rowSums(obj@assays$RNA@layers$counts)+1
data <- LayerData(obj, assay = "RNA", layer = "data")
data <- data[cntxgene>2000,]
list <- getGmt("h.all.v2023.2.Hs.symbols.gmt") #load my signature list
gsva_Par <- gsvaParam(as.matrix(data),  
                       list, 
                       kcdf='Gaussian') 
ssgsea.scores <- gsva(gsva_Par)

By the way, I still have the R 4.3 version with Bioconductor 3.18, I wonder if you can supply the GSVA package version earlier than 1.48. I used the older version before, when I could score 20,000 cells * 30,000 genes in 2 hours, but now I can only download the 1.50 version.
Thank you for your kindly help!

**Comment by rcastelo** [comment]
Dear @sjasws, sorry of the delay in getting back to you. In principle R support vectors with more than 2^31-1 elements, and we try that the implementation exploits that feature. These are a few things you may try:

1. Update to the latest release of the software, i.e., R 4.4.x and GSVA 1.52.x, this is always the recommended solution, and there may be bugfixes that are relevant to the problem you describe.
2. Yesterday we pushed a first partial implementation of the GSVA algorithm that should be able to swiftly work with single-cell data of that size stored in `dgCMatrix` objects. If you have your single-cell data in such an object, you may have a try. To do that you should install the current devel version of the package in R 4.4.x, by doing from R:
    ```
    remotes::install_github("rcastelo/GSVA")
    ```
    and then set the parameters `kcdf="none"` and `sparse=TRUE` when you build the parameter object with `gsvaParam()`.
3. It is strange that you say that a version earlier than 1.48 (1.46?) would allow you to score 20k x 30k cells and the current one doesn't, because in principle, until the last release in April 2024, we have only been fixing bugs, changing the interface and making some optimisations on the ssGSEA method. Maybe, the problem has arisen in an upstream dependency of GSVA. Anyway, you may try fetching the 1.46 version of GSVA as follows:
    ```
    $ git clone git@git.bioconductor.org:packages/GSVA
    $ cd GSVA
    $ git checkout 4036d9f1e3f2b8d7488b9378e18a601ed768f497 ## figure out this hash doing git log and going back to Nov 1, 2022
    $ grep Version DESCRIPTION ## verify version
    Version: 1.46.0
    $ cd ..
    $ R CMD build GSVA
    $ R CMD INSTALL GSVA_1.46.0.tar.gz
    ```
    You should try to build it and run it with R 4.2 (the one that was checked with that Bioconductor version). However, it would not be surprising that somehow it does not work as intended, because going backwards it is not trivial and there may be technical problems along the way.

**Comment by sjasws** [comment]
> Dear @sjasws, sorry of the delay in getting back to you. In principle R support vectors with more than 2^31-1 elements, and we try that the implementation exploits that feature. These are a few things you may try:
> 
> 1. Update to the latest release of the software, i.e., R 4.4.x and GSVA 1.52.x, this is always the recommended solution, and there may be bugfixes that are relevant to the problem you describe.
> 2. Yesterday we pushed a first partial implementation of the GSVA algorithm that should be able to swiftly work with single-cell data of that size stored in `dgCMatrix` objects. If you have your single-cell data in such an object, you may have a try. To do that you should install the current devel version of the package in R 4.4.x, by doing from R:
>    ```
>    remotes::install_github("rcastelo/GSVA")
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    and then set the parameters `kcdf="none"` and `sparse=TRUE` when you build the parameter object with `gsvaParam()`.
> 3. It is strange that you say that a version earlier than 1.48 (1.46?) would allow you to score 20k x 30k cells and the current one doesn't, because in principle, until the last release in April 2024, we have only been fixing bugs, changing the interface and making some optimisations on the ssGSEA method. Maybe, the problem has arisen in an upstream dependency of GSVA. Anyway, you may try fetching the 1.46 version of GSVA as follows:
>    ```
>    $ git clone git@git.bioconductor.org:packages/GSVA
>    $ cd GSVA
>    $ git checkout 4036d9f1e3f2b8d7488b9378e18a601ed768f497 ## figure out this hash doing git log and going back to Nov 1, 2022
>    $ grep Version DESCRIPTION ## verify version
>    Version: 1.46.0
>    $ cd ..
>    $ R CMD build GSVA
>    $ R CMD INSTALL GSVA_1.46.0.tar.gz
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    You should try to build it and run it with R 4.2 (the one that was checked with that Bioconductor version). However, it would not be surprising that somehow it does not work as intended, because going backwards it is not trivial and there may be technical problems along the way.

Dear @rcastelo,
My environment is R 4.4.1, and I have updated the GSVA 1.53.6 package. Then, by setting kcdf="none" and sparse=TRUE, I successfully ran the program in a short time and calculated the GSVA score of 30,000 genes * 80,000 cells from a Seurat dgCMatrix objects with the raw counts. Thank you for your assistance very much!
In addition, I still have some questions and feedback that I hope will be helpful to the GSVA project.
My question is that when setting kcdf="none", which should be used as the input data to be calculated, the raw integer counts or the log-normalized data?
I still encountered the same problem when setting kcdf="Gaussian" in the GSVA 1.53.6 to calculate the score using the Seurat log-normalized data with the error: "negative length vectors are not allowed".
Anyway, I was able to complete the process now, and the result seems very reasonable. Thank you again for your kindly help.

**Comment by rcastelo** [comment]
Hi, I'm glad it worked. GSVA always assumes that the input data is normalized and in general, it is better to provide the data as normalized continuous units of expression, such as with log-normalized data. The setting `kcdf=Gaussian` for sparse data is still not ready in version 1.53.x (hopefullly it will by the next release in October 2024) and that's why you still get an error, but with such a high number of cells, `kcdf="none"` should in principle give reasonable results, as you have observed already. We have not yet extensively tested the procedure you just ran, so please be extra careful in interpreting the results, and do not hesitate to give us feedback if you find anything odd in them.

Two question, could you share:

1. how much time it took to run in your 30k genes x 80k cells data, what OS you use and roughly what hardware (CPU & RAM)?
2. what is the value return by the function `nnzero(x)` with `x` being your `dgCMatrix` object of 30k x 80k?

Thanks for beta-testing this new version of GSVA!

robert.

**Comment by sjasws** [comment]
> Hi, I'm glad it worked. GSVA always assumes that the input data is normalized and in general, it is better to provide the data as normalized continuous units of expression, such as with log-normalized data. The setting `kcdf=Gaussian` for sparse data is still not ready in version 1.53.x (hopefullly it will by the next release in October 2024) and that's why you still get an error, but with such a high number of cells, `kcdf="none"` should in principle give reasonable results, as you have observed already. We have not yet extensively tested the procedure you just ran, so please be extra careful in interpreting the results, and do not hesitate to give us feedback if you find anything odd in them.
> 
> Two question, could you share:
> 
> 1. how much time it took to run in your 30k genes x 80k cells data, what OS you use and roughly what hardware (CPU & RAM)?
> 2. what is the value return by the function `nnzero(x)` with `x` being your `dgCMatrix` object of 30k x 80k?
> 
> Thanks for beta-testing this new version of GSVA!
> 
> robert.

Dear robert,
1. It takes 40min to calculating GSVA scores for 50 gene sets in my 30k genes x 80k cells data, within the Windows OS, CPU AMD Ryzen 7 5700G (8 cores and 16 threads, , but only 1 threads with 4.60 GHz worked in Windows), and RAM 128G (seems like 64G is enough).
2. There are 369,428,314 non-zero values in my dgCMatrix data (contain 2,803,945,048 elements).

**Comment by rcastelo** [comment]
Thank you very much for the information. I'll close the issue, please open a new one if you encounter any further problem or have feature request.
