### ISSUE TITLE
kcdf:  in ssgseaParam，do we still need to set kcdf?

### ISSUE THREAD

**Issue by Stefanhxw** [rcastelo/GSVA#201]
错误于ssgseaParam(exprData = as.matrix(dat), geneSets = gene_set, kcdf = kcdf): 
  参数没有用(kcdf = kcdf)
  

I found that there is no option for the kcdf in ssgsea. i don't know why we needn't to choose that.

**Comment by rcastelo** [comment]
Hi, because this is how the authors of ssGSEA defined the method. The current implementation of ssGSEA in the GSVA package corresponds to the method described in the subsection entited "Signature projection method", from section "Online methods", from the paper by [Barbie et al. (2009)](https://doi.org/10.1038/nature08460). For more authoritative answers on the ssGSEA method you should ask its authors in this [google group](https://groups.google.com/g/gsea-help/search?q=ssgsea) or in this [GitHub repo](https://github.com/broadinstitute/ssGSEA2.0).
