### ISSUE TITLE
Most Data Being Filtered

### ISSUE THREAD

**Issue by abadgerw** [rcastelo/GSVA#204]
@rcastelo I tried running a dataset using the shiny app and nearly all my genes are being filtered indicating they have constant expression. My data is centered at 0 (ie it has both positive and negative values). I also have lots of NAs. Could this potentially be why I'm ending up with nearly all genes filtered? This may relate to the other issue I posted about?

**Comment by rcastelo** [comment]
Hi, the fact that the data is centered at 0, with both positive and negative values, plays in principle no role in the issue you are describing. **If you are using the ssGSEA method, you will get a warning if there are genes with constant expression, but they will not be removed from the analysis**, because ssGSEA makes its calculations independently on each column of the data. The warning is only intended for the user to be aware that such a feature (genes with constant expression) is in the data. A gene is identified by GSVA as having constant expression when:

  1. there are no expression values associated with that gene/protein, because that gene/protein was not expressed in any of the samples, and therefore all its expression values are identical (zero, or some other value of relative expression).
  2. there are expression values associated with that gene/protein, but they are all identical.
  3. there are missing values (`NAs`) and either the non-missing values are all identical, or there are actually no no-missing values.

If you are using the ssGSEA method on the console (not yet in the shiny app), you could build the parameter object with the argument `use="na.rm"` and this would force the GSVA software to perform the ssGSEA calculations discarding the `NA` values.

**Comment by abadgerw** [comment]
Thanks, @rcastelo! I just tried to use the ssgseaParam function with the use argument and received an error stating that use is an unused argument. I'm using version 1.52.3 of the package. Do I need to use the development version to use this argument?

**Comment by rcastelo** [comment]
Oh yes, sorry, I forgot to tell, the handling of missing data with the ssGSEA method was a [feature request](https://github.com/rcastelo/GSVA/issues/174) during this development cycle, and therefore it is currently only available on the devel version of the software, but it will become part of the next release version on October 30th (see Bioconductor [release schedule](https://bioconductor.org/developers/release-schedule)).

**Comment by abadgerw** [comment]
Thank you so much! I really appreciate your help!

**Comment by rcastelo** [comment]
Dear @abadgerw thanks for your patience, a new GSVA version 2.0 has been released yesterday as part of the new [Bioconductor 2.0 release](https://bioconductor.org/news/bioc_3_20_release). In this new version you can handle missing data from both, the ssGSEA as well as the GSVA methods. Please consult the help pages of `ssgseaParam()` and `gsvaParam()` to learn how to handle those missing values. Do not hesitate to report any question or problem you may encounter.
