### ISSUE TITLE
How to retrieve the list of "521 genes with constant expression values throuhgout the samples"

### ISSUE THREAD

**Issue by tyaoi** [rcastelo/GSVA#29]
Dear GSVA developers team

I am a new user of GSVA.
I ran GSVA (Bioconductor version: Release (3.12)) using a set of RNA-seq data from a data base.
Though GSVA scores appears to be normally calculated and stored in an output file, the below messages are returned:

>  警告メッセージ:
> 1:  .filterFeatures(expr, method) で:
>   521 genes with constant expression values throuhgout the samples.
> 2:  .filterFeatures(expr, method) で:
>   Since argument method!="ssgsea", genes with constant expression values are discarded.

(Note: Since R and RStudio has been run on Ubuntu with Japanese language, some of the messages are in Japanese.)

I have a couple of question:

1. Are the obtained scores acceptable results?
2. How can I get the list of "521 genes with constant expression values throughout the samples" ?

Sincerely,

T Yaoi

**Comment by rcastelo** [comment]
hi,

this issues tab is meant for bug reports and features request, for questions such as this one i'd appreciate if next time you post it at the Bioconductor support site at https://support.bioconductor.org because that site is searchable and acts as a knowledge base that helps other users finding answers to their questions without having to ask them a second time.

as per your questions:

(1) your results are fine because the message is just saying that you have a number genes (521 in this case) with constant values and they have been discarded, this is actually good since constant expression does not provide any useful information for estimating pathway activity.

(2) this is not a GSVA-specific question, but the answer would be that if your matrix of expression values is called `y`, then you should calculate the standard deviation for each row (i.e., each gene) and the genes with constant expression are either those with standard deviation equal to zero or those for which it was not possible to calculate it so that the standard deviation is `NA`. An R code to do this would be:

```
sdGenes <- apply(y, 1, sd)
mask <- sdGenes == 0 | is.na(sdGenes)
geneswithconstantexpression <- rownames(y)[mask]
```

**Comment by tyaoi** [comment]
Thank you for your quick response!
Next time I will post on the site to share information with other users.
