### ISSUE TITLE
'names' attribute [244] must be the same length as the vector [8]

### ISSUE THREAD

**Issue by DzmitryGB** [rcastelo/GSVA#35]
Consistently getting the error running GSVA using FPKM matrix (53238 x 11353) and gene set list (244 signatures):

gsva(FPKM, geneSet, method = "gsva", kcdf = "Gaussian", mx.diff = FALSE, parallel.sz=10)

GSVA_1.36.3
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

**Comment by rcastelo** [comment]
hi,

GSVA is building correctly in the Bioconductor servers for the [release](http://bioconductor.org/checkResults/release/bioc-LATEST/GSVA) and the [development](http://bioconductor.org/checkResults/devel/bioc-LATEST/GSVA) branches. The build process includes tests that cover its normal usage. Therefore, the error you are getting is probably related to the input you are giving to the software. Since this is not apparently a bug, I would like to ask you to post a question at the Bioconductor support site at [https://support.bioconductor.org](https://support/bioconductor.org) and before doing that, please read carefully the [Bioconductor posting guide](http://bioconductor.org/help/support/posting-guide), which provides helpful tips to maximize the chance of getting a useful answer. Among those, I would highlight:

* Post all of your R code.
* Include a copy of any error or warning messages that appeared in R.
* Always paste the output of sessionInfo() at the end of your post.

Since it may be difficult for you to provide the input data, at least try to describe it as much as possible.
