### ISSUE TITLE
filter dataset before GSVA

### ISSUE THREAD

**Issue by Lin-Rachmaninoff** [rcastelo/GSVA#43]
Hi,
I have a question about whether to filter my dataset  before GSVA. In the original article, I noticed that the RNA-seq and microarray datasets (commonPickrellHuang) were all filtered before GSVA. GSVA and GSEA shares many similarities. The GSEA website says

>  Typically, the GSEA team runs the analysis on unfiltered data. One suggested approach is to run  GSEA on the unfiltered data.

So I wonder whether GSVA algorithm beneift from filtering poorly expressed genes?

**Comment by rcastelo** [comment]
Hi,

I think the quote you're giving from GSEA refers to a different kind of filtering from the one applied to the datasets that we used to illustrate GSVA. The quote from GSEA probably refers to the filtering derived from a differential expression analysis, in the sense that you should **not** apply GSEA to some subset of differentially expressed genes, but to the whole set of genes you want to analyze. So, the question is, what set of genes do you want to analyze. Do you want to analyze all the genes for which you have a row in your RNA-seq table of counts? What if some of those genes have no positive counts? What if some of those genes have positive but very small counts for only a small fraction of the samples? The answer to these questions is that, in general for any kind of analysis, such as differential expression, GSEA or GSVA, you want to start your analysis with a set of genes with some minimum degree of reliable expression. For instance, having a minimum CPM level of expression in a minimum number samples.

By the way, issues in this GSVA repo are more intended for bug reporting and feature request. For this kind of question it would be better for me if you use the Bioconductor support [site](https://support.bioconductor.org), because questions are more easily discoverable and becomes more unlikely for me to having to answer them twice.

Cheers,

robert.

**Comment by Lin-Rachmaninoff** [comment]
I see. Filtering low expressed genes among all samples is also an important pre-processed step before GSVA. Thanks for your enlightening answer!
