### ISSUE TITLE
Question about the input data and the ssgsea parameters.

### ISSUE THREAD

**Issue by lincj1994** [rcastelo/GSVA#59]
Hi. Thank you for developing and maintaining such a cool tool. I have several questions about the function.
1. In the GSVA manual, it states that several parameters are used only when `method = 'gsva'`. Does that mean I cannot input count data when method = 'ssgsea' since `kcdf` cannot be setted? So what the data format are required when `method = 'ssgsea'`? FPKM, TPM, or CPM? And does it have to be in log scale? 

2. 
```
PathwayGSVA <- gsva(as.matrix(expr_data_TPM), PathwayGMT_ls, method = "ssgsea", parallel.sz = 1,
                    min.sz = 10, max.sz = Inf, verbose = T, kcdf = 'Gaussian', abs.ranking = TRUE)
```
A following question is for such a function listed above, the last two parameters should be removed?

3.
`The workhorse of the GSVA package is the function gsva(), which requires the following two input arguments: A **normalized gene expression dataset**, which can be provided in one of the following containers: ...`
Besides, what does the nomalized dataset mean? Should I normalize the expression dataset before the ssgsea or will the function perform the normalization when running ssgsea?

**Comment by rcastelo** [comment]
Hi, thanks for using GSVA. I'll attempt to answer your questions, but please consider next time using the Bioconductor support site at https://support.bioconductor.org since issues in this GitHub repo are more intended for bug reporting and feature requests.

1. The ssGSEA method was developed by [Barbie et al. (2009)](https://doi.org/10.1038/nature08460) and my understanding is that it requires normalized continuous values of expression. This means logCPM or logTPM values.
2. Yes, whatever you set to those two parameters it will be ignored when you set `method="ssgsea"`.
3. You should normalize the data just as if you were going to perform a differential expression analysis. If you are unfamiliar with this step, please consult the available vast literature on how to prepare data for differential expression analysis.

**Comment by Shicheng-Guo** [comment]
Great question and Answer!! It will be great if normalization can be performed within the gsva function, or with an option, normalization=TRUE. What do you think.

**Comment by rcastelo** [comment]
Thanks for the suggestion, I tend to think that it's better to keep packages being modular and specialized and there're already very good packages for normalization of RNA-seq data, but I'll think about whether there's a real need for that to happen within GSVA. Keep reading the NEWS file at each release!

**Comment by lincj1994** [comment]
Hi. Is log2(FPKM+1) allowed for ssGSEA input?
