### ISSUE TITLE
Leading edge?

### ISSUE THREAD

**Issue by mayanbriller** [rcastelo/GSVA#69]
Hello!
Is there a way to perform leading edge analysis on the ssGSEA results?
I'm looking to find which genes are most prominent in the determination of the enrichment scores
Thanks

**Comment by rcastelo** [comment]
Hi, no, GSVA does not implement such functionality, but I've labeled this issue as a feature request and we'll try to have it implemented for the next release of GSVA in April. In the meantime, to gather insight into what genes may be responsible for the enrichment score of a particular gene set in a given sample, you may use the interactive shiny app of GSVA by typing on the R console:

```
igsva()
```
Use the left panel to load the expression data file in CSV format and the gene sets in GMT format, change the parameters to select 'ssGSEA', and press the button "Run". Once this has finished, you'll see an interactive plot of the distribution of enrichment scores per sample, click on the sample you're interested and you'll get another plot of the cumulative distribution of enrichment scores of the gene sets in that sample. Click on a the gene set of interest and you'll see the distribution of expression values for that gene set, which should give you a hint on why that gene set has that enrichment score.

**Comment by rcastelo** [comment]
Dear @mayanbriller thanks for your patience, this arrives quite late, but yesterday we released a new version 2.0 of GSVA, see https://bioconductor.org/install for installation instructions, and it includes a new function `gsvaEnrichment()` that will allow you to perform leading edge analysis on the GSVA results. It will not produce that analysis of ssGSEA, because as far as I understand the math behind ssGSEA 1.0, all the differences between the ECDFs of the genes inside and outside a gene set of interest, along a ranking of a sample of interets, contribute to the ssGSEA score, so I do not see such a thing as a subset of genes distinctively contributing to the ssGSEA score. Let me know, however, if you know of a specific definition of leading edge analysis for ssGSEA 1.0.
