### ISSUE TITLE
why score of single sample change when sample size change per group?

### ISSUE THREAD

**Issue by FADHLyemen** [rcastelo/GSVA#70]
Hi 
if I have three groups in my dataset, shall I apply gsva in each group separately or shall I do it for all samples at once?
when I added some samples to one group, the socer of samples from the same group was changed, does score change with number of samples in each group?

thank you

**Comment by rcastelo** [comment]
Hi,

I guess you're talking about three groups of samples and therefore, your question is about whether enrichment scores may change by adding or removing samples from your input dataset.

In the case of the default GSVA algorithm, it attempts to take advantage of the information from all available samples, and if all those samples belong to the same experimental design, then you should definitely apply GSVA on all the samples together. This also means that removing or adding samples may affect the enrichment scores that you obtain. This is analogous as doing a differential expression analysis on a dataset with more or fewer samples, which may change the results, because sample size affects the statistical power to detect differentially expressed genes.

If you want to obtain enrichment scores that are unaffected by the available samples at the moment in which you are calculating those scores, then you should use the ssGSEA algorithm, by setting the arguments `method="ssgsea"` and `ssgsea.norm=FALSE`.

**Comment by FADHLyemen** [comment]
Thank you @rcastelo 
usually, do you recommend computing the score for the whole samples using ssGSEA or computing it for different conditions then comparing the score per condition?

**Comment by rcastelo** [comment]
If you use the ssGSEA algorithm with `ssgsea.norm=FALSE`, then it does not matter whether you calculate the scores in one single call to the `gsva()` function, or you do it stepwise, sample by sample, because in that regime, ssGSEA only uses the information available at each individual sample to derive the scores for that sample. If I'm not understanding the question, it'll be easier for me to comment if you post the precise code about which you are formulating the question.

**Comment by FADHLyemen** [comment]
@rcastelo Thank you
