### ISSUE TITLE
ssGSEA gave NAN

### ISSUE THREAD

**Issue by FADHLyemen** [rcastelo/GSVA#72]
![image](https://user-images.githubusercontent.com/23288387/227775853-48645def-4bcd-43a3-82e1-f83c17b253af.png)
the above line gave me NAN, any reason for it, I guess it could be the method or the gene set. any suggestion, I use it for one year and just got this error today.

**Comment by rcastelo** [comment]
If you suspect that the algorithm is not working well, something you can do to try to narrow down the problem, is to use the example of the help page as follows:

```
library(GSVA)
example(gsva)
gsva(y, geneSets, method='ssgsea')
```
and you'll see that this works fine, which means that the problem is probably not with the method but with the input, i.e., either the expression data matrix or the gene sets. By the way, the argument `kcdf="Poisson"` is not used when `method="ssgsea"`. As you'll find described in the documentation, the `kcdf` argument only applies when `method="gsva"`.

For this type of question, I strongly recommend you to post the question at the Bioconductor support site at https://support.bioconductor.org for two main reasons. First, when you post the question you'll use the tag 'gsva', which is followed by other people who is also interested in questions about this package, and this may result in other users who had a similar problem and may give you a solution even faster than me. Second, the Bioconductor support site works as a knowledge base, findable by Googling "bioconductor gsva ....[[question at hand]]", which will help future users with the same problem to find the solution, without having to ask for it. If you decide to have a try, please take a look first to the [FAQ on how to post a question](https://support.bioconductor.org/info/faq/#posts). Following those guidelines greatly helps developers, and other users who may be willing to help, to identify what the problem is, which results in faster answers to the original poster user.

**Comment by FADHLyemen** [comment]
@rcastelo thank you
