### ISSUE TITLE
Do I need to scale the scores for comparison?

### ISSUE THREAD

**Issue by aelhossiny** [rcastelo/GSVA#86]
Hi, Thanks for such an incredible tool! Do I need to scale by row (or column) the output scores after running the `gsva()` to compare the scores between the samples (or on the other hand compare the scores of different genesets with a certain sample)?

Also, another question, if I am using `vst`-normalized expression matrix, which `kcdf` kernel do I use? I assume `Gaussian`?

Thanks

**Comment by rcastelo** [comment]
hi, it's always great to see that GSVA is being useful to so many users. The input expression data should be normalized. For instance, vst-normalized values are fine, and because they are continuous, the default kernel `kcdf="Gaussian"` is correct. Because the input data is normalized, the sample expression profiles should be already comparable between them, and therefore you need not to scale by row or column the resulting enrichment scores. As long as we are talking about enrichment scores derived from the same dataset, they are comparable across samples and gene sets.
