### ISSUE TITLE
Error in GSVA() : long vectors not supported in .C

### ISSUE THREAD

**Issue by YouriTasse** [rcastelo/GSVA#90]
Hi !

I initially posted on the BiocParallel repository (https://github.com/Bioconductor/BiocParallel/issues/255), but I was kindly referred here. 

```
When I run this code : 
# load the dataset 
load("./Wu_V2.RData")
data = mat

## geneset 
gene.excel = read_excel("./c5.xlsx") %>% as.data.frame()

  # set the proper format
  genes = gene.excel[,1] %>% na.omit() %>% as.data.frame()
  genes = list(as.character(genes[,1]))

  nbCores = parallel::detectCores()

### GSVA
gsva1 = gsva(data, #must be a matrix
             genes, #was markers.set
             verbose = TRUE,
             method = "gsva",
             parallel.sz =  nbCores-2) %>% t()
```
I get this error : 

Error : BiocParallel errors
1 remote errors, element index: 1
0 unevaluated and other errors
first remote error:
Error in FUN(...): long vectors (argument 1) are not supported in .C

It only happens with a large datasets.
To be more precise, it happens right after the 100 tasks are completed.

**Comment by rcastelo** [comment]
hi, thanks for reporting the problem, I've pushed a fix to the code of the GSVA algorithm in the devel brach that I think it should sort it out, this is version 1.49.2. However, before I port it to the release branch, I'd appreciate if you could test it with your large dataset. To do that please do the following steps:

1. You need to install the devel version of GSVA, and this requires first installing the current release version of R (because we're in the April-October devel cycle, otherwise in October-April we would use the devel version of R). To install the current release version of R 4.3.1, please go to https://cran.r-project.org and download the installer for your OS.
2. Once you have the current release version of R 4.3.1, install the package 'BiocManager' by doing `install.packages("BiocManager")`.
3. Switch the Bioconductor release version of packages to the development version by doing `BiocManager::install(version="devel")`. Afterwards run `BiocManager::valid()` to ensure all packages are up to date.
4. To use this new devel version of GSVA 1.49.2, you can either wait 24/48 hrs until it becomes available via `BiocManager::install("GSVA")`, or if you want to try it right away, you can install it directly from the GitHub repo with the `remotes` package by doing `remotes::install_github("rcastelo/GSVA")`.

If you prefer that I do the testing, I'd need to have access to your dataset.

**Comment by YouriTasse** [comment]
Hi !

Thank you for your very fast response. 

R/4.2.2. is currently the latest version installed on the cluster I'm using.

Since I don't think I have the required privileges to install R/4.3.1., I will contact the support team and follow-up ASAP

**Comment by YouriTasse** [comment]
Hi !

I followed all the steps and installed GSVA 1.49.2. 
I ran the function with my large datasets and everything worked !

There is no more error !

Thank you very much for your support !

**Comment by rcastelo** [comment]
Excellent, I've fixed it now also in the release version of GSVA 1.48.2, which will become available in the next 24/48 hrs via `BiocManager::install()` from the release version of Bioconductor packages.
